// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA13UJemVr054c-QFzqHh3oJyLUdljWhJw',
    appId: '1:125258690979:web:f02a85f620ef9287572a16',
    messagingSenderId: '125258690979',
    projectId: 'messenger-45455',
    authDomain: 'messenger-45455.firebaseapp.com',
    storageBucket: 'messenger-45455.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBFRRCAX6ypwcABiOJqwlGLH05a1FQsBo',
    appId: '1:125258690979:android:25d687ea695948a9572a16',
    messagingSenderId: '125258690979',
    projectId: 'messenger-45455',
    storageBucket: 'messenger-45455.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZR4RxCh5PItcvOu9JPls__gedT1FIm1w',
    appId: '1:125258690979:ios:fc5d4af4d3432f53572a16',
    messagingSenderId: '125258690979',
    projectId: 'messenger-45455',
    storageBucket: 'messenger-45455.appspot.com',
    iosBundleId: 'com.example.messenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZR4RxCh5PItcvOu9JPls__gedT1FIm1w',
    appId: '1:125258690979:ios:0a1a54fbaf641c23572a16',
    messagingSenderId: '125258690979',
    projectId: 'messenger-45455',
    storageBucket: 'messenger-45455.appspot.com',
    iosBundleId: 'com.example.messenger.RunnerTests',
  );
}
